spring:
  datasource:
    url: jdbc:h2:mem:test
    username: admin
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibaenate.dialect.H2Dialect
  h2:
    console.enabled: true

